### ISSUE TITLE
Notifications/Alerts

### ISSUE THREAD

**Issue by writingpoli** [pubpub/pubpub#1108]
the SAR Editorial Collective would like to **Receive notifications and alerts when new Pubs are submitted and comments added to published Pubs** and the ability to **Alert submitters to Pub status updates** (I think the former will satisfy the latter).

**What would this feature help you accomplish, and why is that important to you?**

- Enable community interaction and tracking. 
- Obviate need to search for submitter email addresses to respond to submissions (no matter how hard we try to get people to leave contact information for us _somewhere_, it's inevitably forgotten. 

**Have you considered any alternative solutions or features?**

- Open to suggestions. 

---

**Any attachments or reference images? (Drag them here)**

**Are there any other products or services that do this well?**

**What's the URL to your PubPub community?**

sareview.org

**Who requested this? (If not you)***

**Comment by idreyn** [comment]
With the usual disclaimers that [our roadmap](https://notes.knowledgefutures.org/pub/pubpub-roadmap/release/28) is not the territory and is always subject to changes and delays...this is actually next on our roadmap! We've started having internal conversations about the scope of our first foray into notifications, and we plan to start implementation by the end of November. This is something lots of folks want and that we're really excited to add (carefully and thoughtfully) to our platform.

As such, hearing about use cases for notifications is super helpful for us right now, and I encourage you to follow up if you have any more thoughts or ideas about what you'd like to see in this feature. Otherwise, you'll hear from us when it launches!

**Comment by gabestein** [comment]
I think we mostly did this between activity and the alerts tray and the new submissions feature!
