### ISSUE TITLE
More Liberal License

### ISSUE THREAD

**Issue by sirinath** [pubpub/pubpub#1181]
In the spirit of integrations and code reuse can the licenses of these projects changed to a more liberal license.

**Comment by metasj** [comment]
Hi Srinath, what do you have in mind?

**Comment by sirinath** [comment]
I am looking for AL2.0 or a https://copyfree.org/ license.

**Comment by gabestein** [comment]
We re-assessed licenses fairly recently, and confirmed that, for now, because of the packages we import, GPL is as liberal as we can go. However, we are attempting to remove as many proprietary dependencies/packages as possible [over the next few years](https://notes.knowledgefutures.org/pub/kkcevu38/release/3), and hope to progressively use more liberal licenses as we go.
