### ISSUE TITLE
Don't allow community admins to create pages or collections with reserved urls

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1370]
On occasion, community admins will create pages or collection layouts with slugs that duplicate reserved URLs (e.g. `search`). When this happens, we serve those pages rather than the reserved URLs, which means community admins can accidentally reduce the functionality of PubPub for their users. We should prevent admins from creating collections or pages with reserved slugs and give a helpful error message when they attempt to do so.

### Business Requirements
- Prevent admins from creating pages or collection layouts (e.g. collection slugs) that are reserved by PubPub.
- Provide a useful error message when admins try to use a reserved slug.
- Update UI text and error messages to use consistent terminology when referring to slugs (I vote for "Link"):
   - Page creation dialogue
   - Page settings
   - Collection settings

### Functional Specs
**TBD**

### Mockups & Copy
> This URL is not available because it is reserved by PubPub.
> This URL is not available because it is in use by another Page or Collection.

<img width="501" alt="Screen Shot 2021-08-03 at 15 26 51" src="https://user-images.githubusercontent.com/639110/128074368-b62608a9-7d6b-4fb3-8a28-25cf90390ddf.png">

<img width="496" alt="Screen Shot 2021-08-03 at 15 27 22" src="https://user-images.githubusercontent.com/639110/128074415-72803731-22a4-4274-b3f5-e6c749b6d7c2.png">

<img width="1135" alt="Screen Shot 2021-08-03 at 15 22 44" src="https://user-images.githubusercontent.com/639110/128073870-bdd17a1f-58cc-464d-88ae-421286cd9f72.png">

<img width="1123" alt="Screen Shot 2021-08-03 at 15 21 46" src="https://user-images.githubusercontent.com/639110/128073757-68fbe6e7-fc44-4278-a438-651746cf0668.png">

### Hints/Thoughts
- Rather than needing to maintain a separate list of reserved URLs, we may be able to build it from `server/routes/index.ts`.
- We already prevent duplicate page/collection slugs from being created, so we can hook into the same error message UIs for those states.
- Bonus if we can cleanup the weird button alignment on the page creation dialogue while we're at it.

**Comment by gabestein** [comment]
Needs list of reserved URLs.

**Comment by qweliant** [comment]
## Write up
### Current behavior 

There are two checks related to what we want to do. These are located in the server/utils/slug.ts They are the `slugIsAvailable` function and `findAcceptableSlug` function. 

`findAcceptableSlug` is invoked on the create methods. The method finds all slugs for the community used by pages or collections. After being spread in an array via a map function, it checks if the slug is in use. If it is, it will look for a hyphenated suffix i.e. -2, -3, -4 and so on, returning the `proposedSlug`. Otherwise it will just return the `desiredSlug`.

We want to change the current behaviour so that an error is thrown on creation(explicit requirement), or PubPub reserved slugs are edited with community suffixes or prefixes(easier time). 

`slugIsAvailable` is called in the update methods for pages and collections. For our goal, we really only need to add more URLs to our reserved list. When the function returns false, it will already throw an error. We need to update how the error message can be passed from `/Users/qweliantanner/Documents/Programs/pubpub/client/containers/DashboardPage/DashboardPage.tsx` and `/Users/qweliantanner/Documents/Programs/pubpub/client/containers/DashboardSettings/CollectionSettings/CollectionDetailsEditor.tsx` so that it reflects the URL is reserved by PubPub
