### ISSUE TITLE
Spike: URL structure

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1507]
We'd like to explore changing the way routing works so that pub URLs can contain the actual slug _and_ a customizable pretty string, e.g. `/pub/r4jk4jkler-acknowledgements/`. PubPub should thus be able to successfully route anything that contains a valid Pub slug, even if you append a random string to the end. If a custom pretty string is set, any URL containing the valid Pub slug should always redirect to whatever the current full custom url is, and that custom pretty string should be set as the canonical url for search engine metadata, crossref deposits, and citations. This is mainly inspired by Medium, and has some nice features, like:

- Having URLs that are simultaneously machine- and human-readable
- Not breaking Pub URLs when you change the permalink, leading to less link rot
- No need to maintain a routing table
- Cool analytics possibilities tracking various links to a post without needing to use the utm format (although this could also be a downside as it's less transparent)

There are a few drawbacks to consider, though:

- Performance. Do we take a hit having to parse the url or having to store a slug and a pretty link separately and then joining them, etc. etc.
- Is it bad for SEO to potentially have lots of different links floating around that point to the same content? (Medium doesn't seem to think so, and I think with a redirect, and `canonical` metadata always pointing to the latest we should be okay, but it's something to look into)
- When someone updates a slug for a previously deposited URL, we may need to warn them to redeposit (or build that into the feature)
- No history of pretty link changes, so less real sense of "canonical" URLs over time
- They are somewhat less human readable than fully "pretty" slugs

**Comment by Dawit-Tegbaru** [comment]
Hey y'all, thanks again for looking into this. The example I shared during office hours was based on this Pub: https://open-knowledge-institutions.pubpub.org/dash/pub/xd8ej8a4. 

I was unable to change the slug to 'acknowledgments' since the slug has already been used elsewhere on PubPub. Using the short title of a pub for the slug is becoming pretty common as a value add. So being able to dress up URLs with terms that are likely to repeat (e.g., 'acknowledgments,' preface,' 'introduction') across PubPub communities would be nice.  

Understanding a solution for the above might take some additional thought, users could in the meantime be instructed to provide a unique custom slug (via the warning if possible). The **leave without changes prompt** is particularly misleading here since the PubPub user doesn't know that their custom URL isn't accepted after hitting the Save button. 

![image](https://user-images.githubusercontent.com/72410195/126352709-5efcc9a5-8805-4154-990a-f668fbd33c81.png)

**Comment by gabestein** [comment]
https://notes.knowledgefutures.org/pub/6955bmvr/draft
