### ISSUE TITLE
page refuses to be deleted

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1530]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. When I go to delete a page, in the edit page at the bottom, and type in the page name, it seems to just refresh the edit page but it doesn't delete the page.
...

### What did you expect to happen?
I expected the page to be deleted. Other pages don't have this problem. But the two below refuse to die. 

### What URL can we use to see the issue?
https://commonplace.knowledgefutures.org/dash/pages/in-the-open
https://commonplace.knowledgefutures.org/dash/pages/inft

### What browser/operating system were you using?
MacOS/Chrome

===

**Comment by idreyn** [comment]
Have you tried asking nicely? 🙂

I see this occasionally and we do to start at least providing a helpful error message — but here's how to do it manually for now. The problem is that there's a Collection using each of these Pages as their landing page. If you visit the Layout tab of a given collection ([e.g. here](https://commonplace.knowledgefutures.org/dash/collection/q3f2xnhw/layout)) and switch to "Use a Layout for this Collection", this _should_ unlink the two and let you delete the Page.

Try it and let me know if it works!

**Comment by sarah-tonin** [comment]
That worked! Thanks Ian :)
