### ISSUE TITLE
Add AMA 11th edition citation style to pub settings

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1600]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?

Add AMA 11th edition citation style to pub settings.

See also: https://github.com/citation-style-language/styles/blob/master/american-medical-association.csl

### What would this enhancement help you accomplish?
AMA citation style is widely used for citing sources in med research. Adding it to PubPub would enable communities with AMA-style requirements to enjoy our citation functionality. 
---

### What's the URL to your PubPub community?
N/A

**Comment by Dawit-Tegbaru** [comment]
Hey @qweliant, thanks again for working on this. I just noticed a small issue that I'm hoping you wouldn't mind looking into. When AMA style is selected for a pub, its citation preview/display includes a number and line break (like it's trying to generate a numbered list). See the screenshot below or check out: https://jbt.pubpub.org/pub/xkqmrgde and please work your magic. We're releasing the journal and issue in ~10 days. 

![image](https://user-images.githubusercontent.com/72410195/144294734-2110f858-6eaf-4be9-a5e1-9de74ec154e9.png)

**Comment by qweliant** [comment]
Will do! I will look into by eod

**Comment by qweliant** [comment]
@Dawit-Tegbaru as i continue to look into it I am fairly confident this is not an issue with our code base. Which is unfortunate. I neither believe it is an issue with the csl file citation js uses to generate ama citation styles. This leads me to think that the issue is with how citaion js. This makes a solution sort of roundabout. 

I could try to intercept the generated citation information or track down where this is an issue in citationjs. I will get back to you when I am more clear on a reasonable solution

**Comment by qweliant** [comment]
Should have a fix up for this pushed to prod in just a bit!
