### ISSUE TITLE
Can't delete Pubs with long names

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1653]
### What went wrong, step-by-step?
1. Copied the title of a Pub with a long name into the deletion box
2. The delete button did not activate.

### What did you expect to happen?
The delete button should activate

### What URL can we use to see the issue?
https://www.crimrxiv.com/dash/pub/uya43dah/settings
https://www.crimrxiv.com/dash/pub/cyew6zho/settings

### What browser/operating system were you using?
Mac OS / Chrome Latest

===

### Who reported this? (If not you)
Scott / crimEmpire

**Comment by idreyn** [comment]
$0.02: I think this interaction is a little too heavyweight and I kind of want to get rid of it altogether. I've always imagined replacing it with the equivalent of a sci-fi control panel where you have to flip four heavy switches (it goes _vwoooooo_) which opens the plastic box around the big red button.

**Comment by idreyn** [comment]
This turns out to be due to hard-to-spot whitespace in the Pub titles: there's a newline in the first one (you can add it to the Blueprint `EditableText` with cmd+enter) and a trailing space in the second. There's more to unpack here but for now I just added some normalization to make the deletion field a little more lenient in 320503a926f338c1f61fcd83e3b260225d223079.
