### ISSUE TITLE
bug: Multi display medium does not display diacritic on capital E (É).

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1705]
### Discussed in https://github.com/pubpub/pubpub/discussions/1704

<div type='discussions-op-text'>

<sup>Originally posted by **reneaudet** December  9, 2021</sup>
Strange (specific) bug: in French we use diacritics, and diacritics on capital letters. I have a Pub with an "É" in its title. It shows well... unless in the public list of pubs (e.g. pubs associated to a collection). All other capital letters with diacritics appear correctly. Maybe it is filtered!? Thanks !

![image](https://user-images.githubusercontent.com/5399642/145450584-a4440cad-cc34-4dcf-bb70-2f5e00e350b5.png)
![image](https://user-images.githubusercontent.com/5399642/145450620-b09a3634-e19d-48be-a0cb-83eeba880c86.png)
![image](https://user-images.githubusercontent.com/5399642/145450669-0dd0ece8-196d-4683-a0bf-7307da6f3a83.png)
</div>

**Comment by djagdish** [comment]
Further inspection revealed that the issue is only in the web version of this typeface. The offline/downloaded version used on standalone apps like Illustrator & Figma does show the correct diacritic rendering for É. 

(from web inspector on Chrome)
![image](https://user-images.githubusercontent.com/316939/148077153-1e666c13-9fa0-422d-9756-40a0ab1cc07a.png)


(screenshot from Figma)
![image](https://user-images.githubusercontent.com/316939/148077219-9139fdbd-2858-47e8-a3b3-afebbb05b731.png)


I've raised a topic for this on the _Type & Typography_ discussion section of Adobe Support Community. That thread can be followed at: https://community.adobe.com/t5/type-typography-discussions/multidisplay-web-version-does-not-show-diacritic-for-%C3%A9-in-medium-font-weight-500-size/td-p/12633420
