### ISSUE TITLE
Improve pub heading structure

### ISSUE THREAD

**Issue by jazairi** [pubpub/pubpub#1898]
### What's your enhancement request?

The pub header component skips a heading level, from `<h1>` for the pub title to `<h3>` for the pub description. Skipping heading levels is considered [bad practice for accessibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes). It also confuses the structure for the remainder of the document, as the pub body would have to begin at `<h3>` or `<h4>` in order to follow the outline.

Additionally, a document should have only one `<h1>` tag, but the formatting toolbar allows users to create multiple `<h1>` tags within the body of the pub. A user should theoretically not be able to create an `<h1>` in the pub body, as one already exists in the pub header.

I would suggest two changes:
1. Remove the heading tag from the pub description, or change it to an `<h2>` tag. (This is perhaps a matter of opinion, but I don't think the description should be a heading.)
2. In the block type selector component, bump each of the generated tags down a level, so that the "Header 1" selection in the generates an `<h2>` tag, "Header 2" generates an `<h3>`, and so on.

### What would this enhancement help you accomplish?

These changes would make our pubs  more easily navigable.

### Any attachments or reference images? (Drag them here)

![Screen Shot 2022-03-24 at 11 53 46 AM](https://user-images.githubusercontent.com/16103405/159966228-23f3537b-d0ea-4776-bce5-e5eb108477fc.png)

### What's the URL to your PubPub community?

My community is not yet public, but this affects all PubPub communities.

**Comment by gabestein** [comment]
Thanks for the request. We discussed it today at our eng meeting, and we're going to implement a more semantic element for the Pub description than an h3.

We're going to leave the header hierarchy in pubs in-tact for now, though. Digging deeper into accessibility discussions, the issue seems to be less with having multiple h1s, and [more with](https://www.accessibility-developer-guide.com/examples/headings/bad-example/) breaking hierarchies and using headers non-semantically in general. Given the lack of consistent answers/approaches from other tools in the space, the minimal impact multiple h1s has on screen readers, the skip links and other features we provide to quickly identify main content, the fact that we can't prevent people from misusing h2-h6, and the awkwardness of calling an h2 a "header 1" in the document, we're going to leave as-is for now and spend the energy on more pressing accessibility concerns.

**Comment by gabestein** [comment]
Just following up on H1s with more nuance on the decision, here: #2303.
