### ISSUE TITLE
Ability to include submitted pubs on journal pages

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#191]
For journal pages, I would like the ability to include not-yet-featured pubs on the front page. I think this would need:
1. An additional option in the journal admin to post to front page but not feature.
2. A tag near the pub title with something like "Under Review". Perhaps customized by the journal.

**Comment by devinberg** [comment]
Another thought on this, these submitted pubs could be listed/labeled as "preprints" which then convert to regular papers upon acceptance in the journal.

**Comment by isTravis** [comment]
So sorry your initial issue never got a response. Agreed - it could be a really useful thing to show submitted articles so that those in the community could also chip in, or at least get a sense of what the journal is working on.

Do you think the author of the work needs to play a role in allowing that or not? I could imagine some authors would not want to advertise which journals they've submitted to if subsequently rejected.

**Comment by devinberg** [comment]
Could be an author control or alternatively, if the journal uses that feature, a statement at submission that pubs submitted to this journal will be listed as preprints prior to acceptance.

Editorial control to list items as preprints/under review would be useful to prevent spam or from listing pubs outside the scope of the journal.

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

Potentially thanks in part to this thread, this is now supported with pages and tags in PubPub V5.
