### ISSUE TITLE
Support bold and italic in Pub titles

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2004]
### What's your enhancement request?
We should support bold and italic text in pub titles.

### What would this enhancement help you accomplish?
In particular, publish papers about model organisms in expected style (e.g. _C. elgans_).

---

Some hilarious complicating factors:
- Make sure styled titles work in auto-generated PDFs (seems fine since it's paged/HTML) and pandoc exports (¯\_(ツ)_/¯)
- For crossref deposits, convert formatting in titles to "[face markup](https://www.crossref.org/documentation/schema-library/face-markup/)", which, of course, is basically pre-HTML5 non-semantic markup
- Ditto-ish for citations via csl-json: https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#html-like-formatting-tags
- I honestly have no idea for html metadata -- since they're mostly parsed by scrapers, my guess is we're gonna want similar to csl-json/crossref `<i>` and `<b>` tags.
- I think that's it?

### Who requested this? (If not you)
Arcadia, Catherine over the years, some others...

**Comment by idreyn** [comment]
Some random thoughts:

- We should do an audit of all the places in the codebase that use Pub titles.
- If we want to continue using the current Pub header title editor, our only option is probably Markdown input and rendering to rich text when blurred. That thing won't support WYSIWYG or keyboard shortcuts.
- Do we want to start supporting TeX in titles while we're at it?
- We'll need to store _at least_ a plain-text rendering of the title at rest to search on. We'll probably want a cached HTML version as well so we can `dangerouslySetInnerHTML` instead of having to render HTML for potentially hundreds of Pub titles on some screens. All of which makes me wonder whether we should build a `Title` table with various cached representations and attach it to the Pub 👀💎

**Comment by avanouse** [comment]
It would be great to have this possibility for the description field as well, and for many of the same reasons.

**Comment by gabestein** [comment]
Enhanced by #2028
