### ISSUE TITLE
Status/roadmap? Seems like features have been removed.

### ISSUE THREAD

**Issue by xicubed** [pubpub/pubpub#210]
Is there some background on this? Finals? Funding? New architecture?

**Comment by isTravis** [comment]
New architecture. We're still chugging! Current progress is taking place for [frontend code here](https://github.com/pubpub/pubpub/tree/v3) and [backend API here](https://github.com/pubpub/pubpub-api/tree/v2). 

Which features in particular are missing for you? We're hoping to get the newest work live in early January. A quick list of things we're getting ready to push live:

- Discussions are getting a major overhaul. 
- We're adding in much more general support for docx files, pdfs, etc. 
- Following behavior is getting a redesign and the landing page is (finally) being replaced with an Activity Feed. 
- Labels for Pubs are added in. 
- The architecture is redesigned to allow for external editors, which opens up the door to offline editors, importing from google docs, etc.
- Backend is moved from Mongo to Postgres, so we have some speedier queries and much saner schema architecture. 

Here's a quick unpolished view of the current v3 Pub page:

<img width="1237" alt="screen shot 2016-12-14 at 9 29 15 am" src="https://cloud.githubusercontent.com/assets/1000455/21363001/aee7c636-c6b8-11e6-8cb0-19305b09a828.png">

**Comment by xicubed** [comment]
I wasn't seeing the differences with red/green highlighting and the split screen with markdown/rendered markdown. 

Was thinking of trying this for course design where instructional designers, faculty, and production staff could collaborate instead of in the multitude of systems that have to be sync'd. So seeing what changed would be crucial especially for QA types. Ultimately the markdown would be rendered out to html and put in the LMS to be taught...

**Comment by isTravis** [comment]
Gotcha. We moved to a WYSIWIG editor shortly after your article went live. Our diff tool wound up taking a bit more work since we weren't just comparing raw markdown text. That is working, but not pushed live yet as it is bundled with a handful of other changes. You can see it here:

![unspecified](https://cloud.githubusercontent.com/assets/1000455/21368920/8a331f1a-c6d2-11e6-85fe-22dee4c49bad.png)

What's the timeline for course design? We're hoping to have most of these changes live in early January. The API will let you grab any of the content/files within a pub and export as HTML if desired, so you could make a quick script to connect PubPub directly to the LMS.

**Comment by xicubed** [comment]
Sounds good. No rush, just exploring options and hoping (thanks for noting) that functionality would re-emerge. I've used Pandoc too to convert md to html but an API sounds even better.
