### ISSUE TITLE
Some regressions

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#223]
I guess these features will be added back soon, but just for myself to keep track. These functions have been removed:

- Editor: plain text as well as WYSISWYG
- Export functionality
- Comments on highlighted text/sorting discussions according to highlights
- DOIs can only be assigned to past versions, but not to the current version of a pub

**Comment by isTravis** [comment]
Removed for the moment, but coming back shortly.

The new architecture supports multiple types of editors, so we'll be adding the WSYWIG editor in addition to others shortly.

You can now directly download files, with serves as some type of export. More organized 'Export as PDF' coming soon.

Commenting coming back soon.

The intent is that DOI's can be assigned to any single _public_ version of a pub. Are you seeing a bug that suggests otherwise?

Thanks!

**Comment by trenkert** [comment]
> The new architecture supports multiple types of editors, so we'll be adding the WSYWIG editor in addition to others shortly.

perfect.

> You can now directly download files, with serves as some type of export.

I've seen that. Is  the ppub file format just md? Or something else?

> The intent is that DOI's can be assigned to any single public version of a pub. Are you seeing a bug that suggests otherwise?

Ah, I think I might have misunderstood the "versions" tab (used to be "history") by thinking it only displays past versions of a pub. 

Maybe it would be a good idea to highlight which version is the most recent one or the one that's currently being viewed. I haven't checked what DOIs look like yet once they're assigned, but in case there is no DOI assigned yet, I think there should be a prominent placeholder saying "no DOI assigned yet" for pubs that are already published.
