### ISSUE TITLE
Author order

### ISSUE THREAD

**Issue by agrignard** [pubpub/pubpub#243]
I just notice that when some author are added the order is kind of arbitrary (note to say random)

Is there a way to fix that? 

Don't know if it's a bug or something that I am missing.

**Comment by r0bis** [comment]
I second that, maybe it could be useful if we could change author order. After all in regular publications it always seems important

**Comment by Kimmichka** [comment]
Hello PubPub team,
One of our collaborators of our journal — r0bis hereabove - who was in contact with Travis from your team in July has kindly informed me that this author order issue was going to be fixed in v4 of PubPub in September and that we would soon be able to reorder the authors names when necessary. 
Are we already on PubPub v4 presently? If we are not, then would you please let me know when we would be able to modify the author order in one of our pubs? 
Thank you very much in advance for your help.
All the best,
Kimmichka

**Comment by isTravis** [comment]
Hi all,

Author order is indeed fixed in v4 and available live now.

**Comment by r0bis** [comment]
Dear Travis,

Many thanks.
 Could you please then migrate all the content below
https://www.pubpub.org/epg to the new vesrion 4, please?
It must be accessible via the version 3 website.
WIth thanks,

Roberts

--
Roberts Klotins

**Comment by Kimmichka** [comment]
Dear Travis,
Many thanks for your help! And many thanks to you too, Roberts, for your watchfulness on this matter! 😊 
I just successfully re-ordered the authors names on our pub. 😊 
All the best,
Kimmichka.
