### ISSUE TITLE
If a pub is in a collection, only the collection title ends up in the `citation_title` and `dc.title` meta tags

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2442]
Heyyy, I'm back again to complain about meta tags, sorry 🙆

### What went wrong, step-by-step?
1. Create pub
2. Add pub to collection (issue here)
3. Title of the pub does not show up in the `citation_title` etc  meta tag.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/21983833/208717476-3d36015a-a7fd-4040-9e0e-39652e2255b9.png">

This is probably due to the earlier changes (on my request, sorry!) here https://github.com/pubpub/pubpub/pull/2307 

I will make a PR to (hopefully) rectify this. Unfortunately it's hard for me to check whether this works!

### What did you expect to happen?
The title shows up in the meta tag

### What URL can we use to see the issue?
https://journal.trialanderror.org/pub/systemic-academia/release/2

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="700" alt="image" src="https://user-images.githubusercontent.com/21983833/208701342-36a75ce5-d15f-466a-8e33-2925359f90f1.png">

**Comment by gabestein** [comment]
Thanks for catching this! I've proposed what I think is a bit of a cleaner version in #2450. Please take a look and feel free to comment. Basically, what I think is sanest (until we do a refactor of the meta entirely) is:

- If the thing is a pub, we use solely the pub title in og:title, dc:title, and citation_title.
- Otherwise, we use solely the collection title for those three.
