### ISSUE TITLE
Pub metadata as YAML metadata block at the beginning of the md file

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#245]
Is it possible to include the pub metadata like authors and abstract as a YAML metadata block in the md file? 

See: http://pandoc.org/MANUAL.html#extension-yaml_metadata_block

This way, it would be much easier to use pandoc templates for exporting pubpub md files.

**Comment by r0bis** [comment]
This would be a nice feature, I agree. Probably a bit complicated one too. Presently I use a separate YAML file (referring to it via pandoc call) to export as PDF. As a result I need to make several adjustments due to my requirements and the fact I want to use `references.bib`:

1.  Remove the title (level 1 heading)
2. Mark the text that I need to be seen as `otherlang` with `[my text that needs to use french hyphenation rules]{lang=fr}`
3. Insert level 1 heading at the end called References

I imagine other special requirements would be there too for other people. I would love to see something like this implemented, where I could maintain YAML header directly in the `main.md` file (e.g. it is there, but is ignored by PubPub rendering processes), but I am afraid that by itself that would not sort out all problems. I would still need to make adjustments 1,2 and 3, so maybe it is easier to just maintain a separate YAML file in my e-book production directory structure.

My YAML header file is here for illustration:
```
---
author: 
- Kxxx Dxxx 
- Dxxx Fxxx 
- Txxx Gxxxx
title: Title of Publication
header-includes:
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}    
    - \fancyhead[RE,RO]{Title of Publication}
    - \fancyhead[LO,LE]{Title of Whole Project}
    - \renewcommand{\headrulewidth}{0.2pt}
date: "July 2, 2017"
lang: [en-GB]
otherlang:  [fr]
bibliography: references.bib
---
```

**Comment by isTravis** [comment]
PubPub v4 no longer supports Markdown, so I am closing this issue. It would be reasonable for a Markdown export to include the metadata associated with a pub as a YAML header though. I will keep that in mind as we push out our Markdown export feature.
