### ISSUE TITLE
Article looks like it is a review of <review of the article>

### ISSUE THREAD

**Issue by dgoodwin208** [pubpub/pubpub#2525]
### What went wrong, step-by-step?
1. After creating a review of article B ("Benchmarks for Climate Tech (V1)", I added a connection showing it was a review.
2. When refreshing B, it shows a connection at the top suggesting it is "↳ A review of" the review
3. When refreshing the review pub, it shows a connection at the _bottom_ suggesting it is "A review of" article B
...

### What did you expect to happen?
I expected the review article to link to the original article, and possible the original to show it had a review, in the same location

### What URL can we use to see the issue?
https://homeworld.pubpub.org/pub/1jqtlce6/draft
https://homeworld.pubpub.org/pub/hy5tvcjj/release/1

### Have any screenshots? (Attach them by dragging the image here)
<img width="751" alt="Screen Shot 2023-02-19 at 4 13 08 PM" src="https://user-images.githubusercontent.com/955132/219975819-78aaf44a-64ce-44e1-b502-929933f039c7.png">

**Comment by gabestein** [comment]
Hello — did you try switching the direction of the Connection in the Connections tab? Connections are bidirectional, so that should solve the issue. If you're creating the review connection from the original article, you'll want it to say "A review of this pub." The language around connection directionality is a little tricky, and we haven't come up with a great alternative yet, so if you have suggestions for improving it, let us know.

<img width="1219" alt="Screenshot 2023-02-21 at 10 10 46" src="https://user-images.githubusercontent.com/639110/220383098-ff5099ee-dae6-44a5-9416-301a698a91fd.png">


I should also note that at the moment, connections show up at the bottom of the parents and top of the children.
