### ISSUE TITLE
Help Page and Documentation

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#262]
Add a help page that provides simple steps for common actions and pathways on PubPub. Add documentation with an FAQ and tips for new communities/authors.

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

In progress at [https://help.pubpub.org](https://help.pubpub.org). Closing because technically it's not a code issue, and we're trying to reserve issues for developers working on PubPub code.
