### ISSUE TITLE
Firebase database

### ISSUE THREAD

**Issue by lucie01** [pubpub/pubpub#266]
Hi everyone.

Is there anyone using firebase as a database for the store? I'm trying without success. 

Thank you for your help.

**Comment by isTravis** [comment]
Hi there,

Could you be more specific about how you're hoping to use firebase? Do you mean as the store for the collaborative editor? Or as the store instead of postgres?

Is your goal just to get pubpub up and running? Or are you trying to use an alternative architecture?

**Comment by lucie01** [comment]
I would like to use firebase instead of Postgres... Just for a test. I'm working on a project with a friend who is a librarian and are implementing this open library (non-profit).

My goal, for now, is just to get pubpub up and running for he makes his on tests. After that, we'll see.

Thank you for your time :)

**Comment by isTravis** [comment]
Unfortunately, it would take a good bit of work to use firebase in place of Postgres. The data is stored and accessed assuming a relational DB, which firebase is not. You would need to rewrite the data model and all of the data queries for firebase to work.

**Comment by lucie01** [comment]
That's OK. I changed to Postgress but now I'm receiving a message "Site not found".
It sounds okay on the console but I receive that message when I access the adress (I'm using the IP addess, not localhost, because I'm using a remote machine).

> NODE_PATH=./client node init.js

----
==> 🌎  API is running on port 9876
==> 💻  Send requests to http://localhost:9876

**Comment by isTravis** [comment]
Ah - yes - that error will show if there is no PubPub community at the given url. In development, we allow you to set the url of the community to load. In your case, no community has been created yet, so we need to do that. 

Change [this line](https://github.com/pubpub/pubpub/blob/master/server/server.js#L93) to be `www.pubpub.org` rather than `dev.pubpub.org`. From there, you can navigate to `/community/create` and create your first community. Once that's done, head back to the line above, and change the url to match whatever domain you set your new community to use. 

I'll work on clarifying this in the documentation.
