### ISSUE TITLE
Pubpub unresponsive

### ISSUE THREAD

**Issue by yaxu** [pubpub/pubpub#2930]
In lieu of reopening #2871, we've been using pubpub for [our conference](https://salon.algorithmicpattern.org/) that has run over the past two weeks, and the papers have often been inaccessible due to frequent outages, such as now.

**Comment by gabestein** [comment]
Hi Alex — my apologies for both the instability and the delay getting back to you. We were hard at work at the tail of last year dramatically improving some of our monitoring and caching systems so that we could better handle an increased load. We believe we have rounded the corner on these issues as of the end of the year, and we will also be working on adding some status pages and other tools to give users a better sense of stability this year.

**Comment by yaxu** [comment]
Thanks for this @gabestein, overall using pubpub as a platform for our event went very well. I'm just unsure how to pay for the extra DOIs we generated!
