### ISSUE TITLE
Error in loading collection overview

### ISSUE THREAD

**Issue by sheishistoric** [pubpub/pubpub#3078]
### What went wrong, step-by-step?

1. User wants to access collection via Community Overview Dashboard
2. User selects the collection from the dashboard
3. Collection Overview Dashboard does not load (returns a 503 error).

### What did you expect to happen?
Collection Overview Dashboard would load, displaying collection overview. 

### What URL can we use to see the issue?
https://openrewi.pubpub.org/dash/collection/verwaltungsrecht-in-der-klausur

### What browser/operating system were you using?
Firefox

## Optional
Given the size of the collection (121 pubs), it looks like the system is timing out the request. Not sure if this is true of large collections in general?

### Have any screenshots? (Attach them by dragging the image here)
<img width="1228" alt="Screen Shot 2024-04-26 at 9 30 34 AM" src="https://github.com/pubpub/pubpub/assets/8959416/f851aad0-bf54-40b4-91e6-ab03ac674ef6">
<img width="1227" alt="Screen Shot 2024-04-26 at 9 31 03 AM" src="https://github.com/pubpub/pubpub/assets/8959416/b7210984-3468-4d8f-83dd-4ba05153990e">

### Who reported this? (If not you)
Nikolas//OpenRewi

**Comment by gabestein** [comment]
@tefkah — let's chat about this when you get back. Getting Fastly cache chunking errors sometimes, other times timeouts in the app itself.

**Comment by tefkah** [comment]
Hmmm interesting. I doubt this has to do with the size of the collection tbh, a rather gigantic collection like https://baas.aas.org/dash/collection/vol-54-issue-8/overview loads fine

**Comment by tefkah** [comment]
I think i fixed this, i think it's due to two things
- rather large collection
- relatively lot of members/attributions

by default, when fetching the pubs for the overview, we fetch every collection pub for every pub, and for every collection pub we fetch the entire collection, and for every collection we fetch every member/attribution

this collection had something like 140 pubs and like  40ish attributions + members
this ends up fetching ~5-6000 members/users/attributions, which i think is why this takes so long to complete.

i put up a PR that adds extra configuration to `getPubs`, which allows you to just fetch the collection for a collectionPub, which is a lot lighter. 

we can't get away with not fetching the collection for each collectionpub for each pub, as it is needed to show what other primary collection a pub is in, if the current collection is not the primary collection. otherwise it always shows the current collection to be the primary collection.
