### ISSUE TITLE
Saving doesn't seem to go through; dupes easy; needs confirmation dialogue

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#338]
While logged in as a user and admin, and saving a private [pub](https://kfg.mit.edu/pub/handbook/draft), I did not get a confirmation dialogue (and stayed on the screen showing public/private save options).   The result was saving a number of identical versions.

A confirmation dialogue when saving works; a warning when saving an identical revision; and explicitly replacing the save dialogue with some message (either one of the above or an error) could finesse this issue.

**Comment by gabestein** [comment]
I believe the issue with the dialogue not disappearing upon success was fixed in https://github.com/pubpub/pubpub/commit/570fbd39d570cfae0818a4fd6ceb47668ea9cbb0
and
https://github.com/pubpub/pubpub/commit/a19ec149de14e5153ed98e22a4bc00d4bb2dd7bc

However, we should do a better job of displaying errors when publishing fails. We'll roll this as an enhancement into v6.

**Comment by gabestein** [comment]
With V6 now launched, saves happen automatically and there is confirmation for failed merges across branches. It's still possible to lose saves without realizing it if your local changes haven't synced yet, which we'll address in #447.
