### ISSUE TITLE
Allow custom iFrame height

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#340]
**Requested By**
RTI Press, Collective Wisdom

**Story**
As an author, I'd like to be able to embed iFrames at any height, so readers don't have to scroll to see the embeds.

**Tech Spec**
- Box next to slider that allows user to set custom pixel height, overriding slider height
- Should track with slider height
- Slider should become inactive when user sets height over slider max

**Comment by isTravis** [comment]
Feature added in 2b400ce. Rather than making the slider inactive (i.e. unclickable) at heights over `slider-max`, I set the slider value to `Math.min(800, currentVal)`. Same for values less than `slider-min` (150px). Let me know how that looks, and feel free to re-open the issue if UI tweaks are needed.

![iframeHeight](https://user-images.githubusercontent.com/1000455/57891959-3e7f1500-780b-11e9-95bd-e4f5e9155e26.gif)

**Comment by gabestein** [comment]
This looks good -- just one weird hiccup I encountered. To repro:

1. Select all in the new `pixels` box
2. Try to enter in 1000
3. It will end up entering 5000

Any number when you select all will start with 50 and remove the first number, because the minimum it will accept is 50 (ie 675 --> 5075).

Related, trying to change a number where the last two digits are < 50 by cursoring to the first numeral, deleting it, and adding a numeral gives weird results. (ie, trying to change 800 to 100 via this method results in 501).

Repro:

1. Drag slider to left so value is 800.
2. Focus on `pixels` box.
3. Using arrows, move cursor to before the 8.
4. Delete.
5. Type 1.

**Comment by isTravis** [comment]
Good catches. Both are fixed with 01c37743842563f29dca8afa85eb93c715f731ca.
