### ISSUE TITLE
Contributors list not updated?

### ISSUE THREAD

**Issue by WheezePuppet** [pubpub/pubpub#344]
As an end user, I created a new PubPub document, added content, then shared it with my work group. Someone else added content, and the content appeared for me when I refreshed, but the "Contributors" list in the upper-right of the page still has only me. Shouldn't it also include this additional person who added content?

**Comment by isTravis** [comment]
Thanks for posting the issue. I think there are UX improvements that could be made here, but from what you've described, I believe this is expected behavior. PubPub separates the concept of 'Sharing' and 'Attribution'. Sharing is about access to the PubPub document - whereas Attribution is about assigning credit for contribution. 

You may have someone editing a document on PubPub that you do not want listed as an explicit contributor (e.g. a copy-editor). And vice versa, you may have a co-author that is not involved with editing the content on PubPub. 

In the image below, you can see there is an 'Attribution' section separate from the 'Sharing' section. This is where you can add individuals (whether they have a PubPub account or not) to display as contributors.

<img width="909" alt="Screen Shot 2019-05-24 at 2 28 51 PM" src="https://user-images.githubusercontent.com/1000455/58349244-c62eda00-7e30-11e9-9510-fd453b397858.png">

All that said, perhaps an improvement would be to describe these differences on the 'Sharing' and 'Attribution' panels directly.

**Comment by gabestein** [comment]
Closing, as this is expected behavior and recent re-org of management panels may help resolve some confusion.
