### ISSUE TITLE
Tracking settings page

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#392]
Part of the GDPR requirement is that we make it as easy to opt out of tracking as it was to opt in. The best sites I've seen solve this by creating a page for tracking with checkboxes that allow people to easily opt-out of anything they had previously opted into.

So, we should create a page (`/tracking`?) that includes:

- Check-boxes for opting in or out of all tracking services (I think just Keen right now?)
- A button with a mailto that allows users to easily get in touch if they have general GDPR objections
- A link to our privacy policy
- A link to our GDPR compliance page

And we should link to this page from the global footer (perhaps next to terms).

Stretch: in an ideal world, we would track this status anonymous users with a cookie (without an ID!) and logged-in users with a DB column. This page would recognize if someone is logged in, and update the DB column if so (and vice versa).

Stretch 2: In an ideal world, we would replicate the contents of this page on a logged-in users' profile page.

**Comment by idreyn** [comment]
> Stretch 2: In an ideal world, we would replicate the contents of this page on a logged-in users' profile page.

I was thinking about this, but I think what we're moving towards is breaking the user profile page into "profile" and "settings", where the dividing line is roughly whether a given option has public-facing consequences or not. This seems like a common pattern on other sites, but:

1. I always click on the wrong one, and it's always annoying to get between the two.
2. We don't currently have enough "settings" for me to feel like it's justified to create that page yet. Once we have an automated user deletion function (rather than just a "click here to email us" button) I think we'd be closer to critical mass for that.
