### ISSUE TITLE
Footnote/citation occlusion and direction sensing leads to unreadable notes

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#448]
## Who requested
Gabe

## What is it?
Footnote/citation popovers appear to always expand up rather than sensing whether they should pop up or down. Additionally, z-index issues cause them to pop up under some multimedia or sidebar items.

## What is expected?
Popovers sense when they would be occluded by the top or bottom of the browser and pop up or down accordingly; popovers are ordered to pop over sidebars and media.

**Comment by gabestein** [comment]
Just focus on z-index

**Comment by gabestein** [comment]
Had a chance to take a look at this, and I need a bit of help thinking through this one. First, I do think we should probably do something.

There are two cases where the occlusion is happening, and one of them there's no workaround for.

### Case 1: Pub Header 

<img width="640" alt="Screen Shot 2019-08-01 at 9 34 36 AM" src="https://user-images.githubusercontent.com/639110/62297800-d5895f80-b43f-11e9-8f3e-3d76fd8a6435.png">

Unfortunately, this isn't as simple as bumping up the footnote's z-index, because occlusion by the editing bar is the expected behavior on draft branches, but not on public branches. If you re-arrange z-indexes so only the header bar stacks on top of the footnote/citation tooltip, you get this quite weird experience: 

<img width="1098" alt="Screen Shot 2019-08-01 at 9 21 37 AM" src="https://user-images.githubusercontent.com/639110/62297505-5ac04480-b43f-11e9-8e16-6c0dfda6ad26.png">

Any thoughts on what to do here, @djagdish?

### Case 2: Open comment

<img width="687" alt="Screen Shot 2019-08-01 at 9 34 10 AM" src="https://user-images.githubusercontent.com/639110/62297880-f3ef5b00-b43f-11e9-89e3-3b46ee3d0d22.png">

This one feels less urgent because there's a simple workaround: close the comment. Closed comments don't occlude the footnote. But the fix is also very simple: bump the `.footnote-wrapper` class z-index to anything greater than 0.

**Comment by isTravis** [comment]
At the moment, the content of footnotes and citations are inline. When you hover a superscript, we simply set that inline content from `display: none` to `display: block`. This makes it hard/impossible to use any of the Blueprint positioning tools. 

There are a few other things we eventually want hover interactions for. For example permalink icons when you hover headers or fullscreen icon when you hover images. I think the proper and stable solution here is to build a more general 'hover' component that specifically watches for certain hover events, and then renders content over the Prosemirror body appropriately. 

This would give us a single paradigm for all hover events, simplify the rendering Prosemirror has to do for footnotes (i.e. just a superscript, rather than a superscript with hidden inline content), and remove some of the errors we have with printing where the inline content is rendered directly in-body.

Such a structure would need to be built for moving away from NodeViews anyways - so we may not want to spend extra effort here if the NodeView switch is within a couple months (which I hope it would be).

**Comment by gabestein** [comment]
Yup, that makes sense. 

I still think we should do something about case 1 in the short-term, because right now you functionally can't create a footnote/citation in the first few lines of a pub, because it will always be occluded by the header. Are we okay with the wonkiness of it going behind the editor bar for the next few months until we can implement the hover component as described?

**Comment by gabestein** [comment]
We're gonna make it default to opening down.
