### ISSUE TITLE
Lost steps should be stored locally so they can be re-merged once user is back online

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#459]

**Comment by isTravis** [comment]
The changes introduced in #472 make it impossible to make further steps once an error has been fired. So, I do not believe new steps could be lost due to an error. In combination with the 'Unsaved changes' dialog popup, I believe we have most bases covered that lead to this situation.

The remaining case would be a situation where someone without internet connectivity quit their browser, ignoring messages - or had an unexpected computer shutdown. In that situation, the cleanest path to me feels like creating a new 'restored' branch that the user can decide how to merge (rather than forcing steps to merge into the current branch). 

Given those points, I'd like to close this for now, and re-open if we find this is still a significant issue when we have branch merge/diffing available.
