### ISSUE TITLE
Investigate collaborative editor instability

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#495]

**Comment by isTravis** [comment]
Updated in pubpub/editor and pushed to production here f6333cd7e5d43d4ddeaad67387dc6a01d962ec06.

The bug was a relatively new regression due to this commit pubpub/pubpub-editor@2c75b475458557925e2a29df87eded33fc9850e0. The issue was that `Math.max()` was silently converting to an array of Strings (e.g. `["1", "2", "3"]`) to a Number (which is the type we wanted in the end), which our reduce function wasn't doing.
