### ISSUE TITLE
wishlist: docker image/Dockerfile

### ISSUE THREAD

**Issue by yarikoptic** [pubpub/pubpub#52]
It would be great if anyone could give a shot to pubpub by running a oneliner without needing to deal with npm etc.  Should be easily doable with a pre-crafted docker image... and probably would be of benefit to carry the Dockerfile which would be used to generate such an image. 

Cheers and thanks!

**Comment by ThariqS** [comment]
This is definitely something we wanted to do. @colbygk was looking into it for media lab demo purposes.

One annoying thing is that we still have a firebase dependency because of firepad and that won't be self-contained in the docker file.

We are looking to swap out firebase at some point though, we just need a real time db like couchdb with an adapter for firepad written for it, like in this file: https://github.com/firebase/firepad/blob/master/lib/firebase-adapter.js If anyone is interested in tackling this sooner rather than later, let me know!

**Comment by colbygk** [comment]
Hi, this spurred me into working on this the other day.  It's pretty straight forward and I'll try to put in a pull request this week, depending on other issues. One thing that slowed me down was getting a provisioned sendgrid account. I may put in some updates to use other transactional email handlers if it looks like I can fit them in soon (mailchimp/mandrill and an Amazon SES).

**Comment by ThariqS** [comment]
that would be awesome, thank you!

**Comment by tomerweller** [comment]
These are two separate independent issues. The firebase dependency can be provided to the container via an environment variable or a command line argument. It doesn't block creating a Dockerfile.

**Comment by colbygk** [comment]
Yes, not dependent, though correctly testing to see if they work would require having an end point to test against.

**Comment by isTravis** [comment]
Closing the issue as it's been stale for over a year.

**Comment by yarikoptic** [comment]
FWIW: being "stale" doesn't mean it was resolved.  It's pity to see that it wasn't properly addressed.
