### ISSUE TITLE
Implement Editor toolbar and formatting designs

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#539]
Deepak's new designs for footnotes and citations are available on Figma. Implement these to be functional in code.

**Comment by gabestein** [comment]
While we're implementing here, there does appear to be some instability with footnotes and citations, including:

- Frequent failures to parse DOIs and fetch results
- Errors when adding structured text
- That recurring issue where selecting a footnote/citation and then another of the same type doesn't update the toolbar (I think the plan was to fix that with this implementation)

**Comment by gabestein** [comment]
Good suggestion from Hanna:

"When I write/edit a pub and insert a footnote link, I have to go back to the number inserted in the text and click on it in order to be able to insert a footnote. It would be helpful if, when inserting a footnote, I would automatically be in the editor and could directly type in the footnote text."

IE, clicking footnote in the editor bar would ideally focus on the created footnote node and bring you into the footnote text editor in the editor bar.
