### ISSUE TITLE
iOS dropdown menus and download buttons broken

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#553]
**What went wrong, step-by-step?**
- Auto-generated downloads can’t be made on iOS — I haven’t been able to download on Safari, Chrome or any other iOS/iPadOS browser. 
- It seems it has something to do with popover/window blocking. 
- Note that the “Formatted Download”, if it exists, *does* work. I am using iOS 13/iPadOS 13.

Furthermore, 
- The drop-down menu bar items, and items like the download button, aren’t working on Safari on macOS. They work fine on Chrome for macOS. Note that I am on the latest Catalina beta (10).

**What URL can we use to see the issue?**
Any pub

**What browser/operating system were you using?**
Safari on Mac and iOS. All browsers on iOS

**Have any screenshots? (Attach them by dragging the image here)**
https://assets.pubpub.org/_testing/61570009582029.mp4

**Who reported this? (If not you)**
Jeff Pooley

**Comment by idreyn** [comment]
> Auto-generated downloads can’t be made on iOS — I haven’t been able to download on Safari, Chrome or any other iOS/iPadOS browser.

This is because Safari [blocks](https://stackoverflow.com/questions/30871799/safari-on-mobile-blocks-window-open) any calls to `window.open()` that does not originate in a user-generated event handler, e.g. an `onclick` callback. Because the exporter has an intrinsic delay while it sends the Pub to the conversion worker, we'll need to add a second button for mobile Safari users to click to actually download the file.

> The drop-down menu bar items, and items like the download button, aren’t working on Safari on macOS. They work fine on Chrome for macOS. Note that I am on the latest Catalina beta (10).

I can't reproduce this on Mojave, and I'm hesitant to download Catalina for the time being. I'd be curious to know if this has gone away in the final release. Also, the attached screencap looks like it's recorded from an iPad which is connected to a Mac via a remote desktop client — that might be the source of the problem as well.

**Comment by jeffpooley** [comment]
Glad to hear there’s a plan for iOS/iPadOS browsers!

And I just updated to the full Catalina release, and I’m happy to report that Safari for macOS downloads are working again!

The new import, by the way, is both slick and very functional: well done!
