### ISSUE TITLE
Page Improvements

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#555]
I'm adding a big list of page improvements here to be split later.

- upgrade banner blocks to be homepage-style (two buttons, logo and image, header and description)
- allow individual pages to overwrite global header with a banner block a la the homepage
- sometimes the block menu bar does not stick to top when you're scrolling down through blocks -- can't quite figure out the repro conditions, but it happens fairly often in text blocks
- scrolling up to hit save button is quite inconvenient, should be sticky since it doesn't auto-save
- no history — once you make a change, it’s gone
- multiple people should be able to work on a page at same time without risk of conflict
- paragraphs around floated images don’t clear well
- text styling doesn’t match new pub styling and is due for a refresh
- drag and drop seems to be partly broken for pub and page ordering — items disappear when you try to drag them and sometimes the page scrolls (happens for nav in site settings, too)
- the link tooltip popup does not appear when you add a link to a text block and text blogs don’t show link field when you first click — have to then cursor over them
- no good way to add a link to images (same with pubs, but more important for pages)
- image/video min size is too large. Hard to have small images.

**Comment by coahearn** [comment]
- would be helpful to have block (or even whole page) templates you can save and duplicate (pub size, block order, details show/not shown, collections filters in blocks)
- Ability to have more than 10 pubs in a block
- If new pubs are created since you opened a page, they don't show up under the list of available pubs to include in a block. You need to save your page and then refresh in order to see them in the list. 
- It's a little confusing for users that when selecting a pubs block we refer to two styles as "default" and "table of contents" but then don't use those same terms anywhere else. TOC in the pubs block is the "small" option. Perhaps the current "minimal" and "small" options should switch if we want to stick with those designations.

Will add more as I think of or run into them...

**Comment by metasj** [comment]
+1 for having more than 10 pubs in a block

**Comment by Honoluluskye** [comment]
Hard to find how to add a new collection. I tried to search through all the help literature that I could find but it all seemed outdated from 2018...

**Comment by gabestein** [comment]
Many of these have been addressed as of #1300. The rest, I think, are larger projects we have explicit roadmap items for that will go through a more thorough development process. Thus, I am closing this issue.
