### ISSUE TITLE
Editor becomes unfocused in some cases in Firefox

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#665]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Visit any pub in Firefox
2. Create a line of text with a link
3. Click the link in the text so that the inline link menu appears
4. Click the editor again to get out of the inline link menu
5. Click backspace
6. Browser will go back

**What URL can we use to see the issue?**
Any pub

**What browser/operating system were you using?**
Max / Firefox latest

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Gus

**Comment by idreyn** [comment]
I just checked and #673 will solve the specific problem with the link menu described here.

That said, I use Firefox every day and there's another case that seems worth solving. Sometimes I'll make a selection, hit backspace and accidentally navigate back instead of deleting text. This happens exactly in the case where the selection is started with the "pointer" cursor rather than the "text" one, so something is going on where Firefox (but not Chrome) lets you select text inside a`contenteditable` element without selecting inside the editable region somehow. The fix could be a CSS one-liner or a bunch of JS event munging.

**Comment by idreyn** [comment]
Terrifyingly, `user-select` has not been standardized as a CSS property yet, and so applying Chrome's desirable behavior of using `user-select: contain` on `contenteditable` elements is currently impossible in Firefox. Seems like there might not be a straightforward solution to this.
