### ISSUE TITLE
Tracking Changes and Copy Editing

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#70]
Many have been asking for (and we have been finding ourselves needing) a track changes or 'suggest edits' mode. This mode would be used by copy editors (either assigned by the author or associated with a journal) as well as the general public (if the pub is published) for suggesting updates, typo fixes, and document changes.

An important note here is the pending inclusions of documents being 'forkable' and 'branchable'. Branches of a document could be used to provide a translated version, a jargon-free version, or a version tailored to a certain audience.

So, there seem to be three 'types' of people who may be considered copy editors (i.e. those who suggest edits, not those with write-access to the main document).
1. those explicitly designated by the author (traditional copy-editors)
2. those from the public who offer improvements and changes to the pub (open contributors)
3. those providing entirely new versions of the original document (translators, journalists, etc)

The first question: **Do all of these 'editors' use the same workflow?** Should different toolsets or flows be designed for these purposes, or are they all roughly the same? 

The obvious predecessors for copy-editing are Google Docs (Suggesting mode) and Microsoft Word (track changes). However, the obvious predecessor for new versions is git and Github's pull-request flow. 

So, a couple options:
## Option 1

Mimic git behavior. All copy-edits are created on cloned (forked) documents. Merges are added back in with a similar pull-request workflow. (All git like features would be behind a UI - the user would never deal with managing git commands unless they chose to write in emacs or Sublimetext).
**Pros**
- Similar workflow as git and github. Lots of asynchronous copy-edits can be made and then merged back into the main document - or live as independent branches.
- Great offline compatibility
  **Cons**  
- Git merging within a document not clear (how do I accept changes on lines 1-10, but not the following changes?)
- Asynchrony introduces some frustrations. The possibility of getting 10 pull-requests all changing the same typo exists (which wouldn't happen on a shared and syned Google Doc-like experience)
## Option 2

Separate workflows. Branching exists, and 'suggest edits' mode exists. Suggest edits mode is implemented within the markdown - and provides a shared place for all (both public and assigned copy-editors. Individual changes are accepted/rejected by the author.
**Pros**
- Fast, unified suggestion space for all users. No case of multiple copies providing the same changes.
- Simpler author experience. Simply go to your original document and see the suggested changes.
  **Cons** 
- No offline support

Within this, there are two suboptions relating to the implementation of the suggesting mode: 

**Option 2a:** Changes are made directly in the markdown (a la Google Doc suggest edits). This is nice in that the editor can just type however they like and the updates will be marked as suggestions which can be accepted or denied. 
**Pro:** The editing experience is fluid and obvious.
**Con:** The document could get really messy (nothing to stop someone from adding 10,000 exclamation points to the top of your document).

**Options 2b:** Copy-editors have to select the text they wish to edit and click 'suggest edit'. They get a popup window that stores the text they highlighted and the associated change. 
**Pro:** It doesn't actually mess with the markdown.
**Con:** A more involved (an extra highlight and click) experience for the copy-editor

All feedback and insights welcome. Open to any other examples of people who nail the copy-editing experience for documents that have versions, etc. 

I'll post updates here as we settle on a decision.

**Comment by r0bis** [comment]
It is very useful to think about this. Currently the strength is that **versions have to be saved explicitly**. Google docs "versions" get unmanageable quickly with many suggests and difficulty to find out which version is which. We have not yet used in practice the review process offered by PubPub, but perhaps that would be the `intentional  suggest` workflow. I.e. the invited reviewer leaves comments on specific blocks of text that seem of importance; it is up to the author(s) then to actually incorporate the suggestion. With this it is quite important to keep track (i.e. lable/archive) the proposals, so that they can be put away when implemented or rejected (explaining why), but still available for later retrieval in case  of similar requests for changes popping up. I think letting text be managed by github like process is not feasible for 2 reasons:
1. as you pointed out - it can be tricky to distinguish which changes get implemented. This is not software code lines, this is people writing free text and I could imagine the mess created when 'lines' get substituted.
2. I cannot imagine authors from non-software related fields to not get confused about how git style changes, merging and branching, etc, would work. It will be too anxiety provoking and people will likely not use this and keep struggling with Word or Google Docs - which are messy, but more accessible.

For these reasons I think you currently might have something more workable than either GoogleDocs or mimicking git. Keep authors in charge and have a system where suggested edits are available, can be categorised and archived, but have to be implemented in actual markdown by the authors.

**Comment by gabestein** [comment]
_We're moving non-code discussion of features and bugs to [Discoure](https://discourse.knowledgefutures.org). This issue has been re-opened and updated [here](https://discourse.knowledgefutures.org/t/track-changes-suggestions-and-copyediting-modes/19)_
