### ISSUE TITLE
Configuring firebase url

### ISSUE THREAD

**Issue by Yomguithereal** [pubpub/pubpub#74]
Hello @pubpub. I am hitting another problem related to Firebase. It seems that it's not possible to set the url without using env variables yet and that in dev mode, the url fallbacks to an hardcoded url hitting your accounts. I found how to change that regarding the API and can submit a pull request but things got a little bit more hazy concerning the client and I am unsure how I should proceed not to leak the configuration completely to the client.

**Comment by ThariqS** [comment]
@Yomguithereal Sorry for the late reply! Yeah this part is not completely DRY, but for the frontend basically you just want to edit this file here: https://github.com/pubpub/pubpub/blob/master/src/config.js

The client only needs the URL of the firebase it needs to connect to, and no secrets, since it is given a signed token.

**Comment by Yomguithereal** [comment]
That's indeed what I was thinking. The issue with this file is that it relies only on the environment and importing the API config within it would mean to leak crucial information to the client. So I was wondering which strategy you wanted to implement here: webpack injection somehow, environment fallback on the config etc.

**Comment by isTravis** [comment]
Closing as Firebase is no longer used and the architecture has been updated.
