### ISSUE TITLE
Feature Request: Integration with Grammarly (or a similar service?)

### ISSUE THREAD

**Issue by gsarma** [pubpub/pubpub#78]
One virtue of traditional journals is copy editing.  I've wondered for a while if a way to keep costs down with the new wave of online-only open-access journals, and of course, the even more innovative and forward thinking platforms like PubPub would be to offer integration with a service like Grammarly.  I realize that it most likely couldn't be free (unless through an arrangement with MIT, or some other way), but it could be an optional service that some users would be willing to pay for.  I suspect that this question overlaps with the thread at issue #55 concerning assigning DOIs.  

Unfortunately, it [appears](https://www.grammarly.com/answers/questions/913-api/) that Grammarly does not yet have an API.  But I thought I would raise this issue to see if anyone had any thoughts.

**Comment by r0bis** [comment]
I think that PubPub is a fantastic project. I would rather this project remains independent from third parties in two aspects. First is about having a **third party that is paid for** could set a bad precedent - there could be more services added on like that and it would dissolve the original impetus of PubPub - a strong, open source tool benefiting from the reputation of MiT. Secondly there is the huge **privacy** issue. The text obviously is processed by Grammarly in order to be checked; how many people might be put off by that? And maybe lastly - I believe that people can either check grammar themselves, or if they choose so they can already use Grammarly for suggestions by using copy/paste - in a separate window that is open for Grammarly. Therefore I do not see much value added by the hassle of integrating this third party.

**Comment by isTravis** [comment]
I agree with @r0bis on this issue. I'm going to close this because it is stale. If conversation picks back up, happy to reopen.
