### ISSUE TITLE
Better editing of title (url) when in draft phase

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#81]
Currently the first step to creating a pub is to give it a title which then auto-populates the URL slug. One issue here is that often the title of a manuscript would be changed while writing. This is possible, however, the URL does not change with it.

Perhaps an alternative would be to use a unique/random URL while in draft mode and then "lock down" the URL when publishing.

**Comment by isTravis** [comment]
Yep - absolutely. This has been on my mind for a bit now. The pub URL will default to a random hash and you may change it as much as you like (to urls that haven't been used yet, of course). At the moment of 'publishing' though, the url becomes frozen so that it is stable. We'll make this clear at the moment of publication.

**Comment by isTravis** [comment]
Architecture2 now assigns a random hash as the default URL. This URL can be changed as often as your heart desires **before publication**. Once published the URL is fixed and cannot be changed.
