### ISSUE TITLE
Minimum requirements for listing a journal

### ISSUE THREAD

**Issue by gsarma** [pubpub/pubpub#83]
Looking through the current list of journals, it seems that only a small minority have any kind of activity or non-zero number of publications.  I think it would come across better for the platform if there were some minimum requirements in order for a journal to be listed.  It could be as simple as having a single publication.

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

Thanks for your feedback. Since the platform has grown to have more active communities, and we've changed the way we're thinking about the platform and listing communities, we're closing this issue for now.
