### ISSUE TITLE
Migrating existing journals to PubPub

### ISSUE THREAD

**Issue by gsarma** [pubpub/pubpub#84]
This is slightly ambitious, but I think it’s worth considering building an import system for existing journals to transition to PubPub.  There are a number of new, online-only journals that could reduce their overhead even more by using PubPub, as well as benefit from the novel journalistic practices that it allows for.  

The main issue, of course, is how to handle previous publications.  A straightforward way to do this would be for PubPub to display standalone PDFs in the main pane of what would normally be Markdown, with the usual comment fields on the RHS.  

This way, pre-existing publications would still benefit from an ongoing comment system, and the task of new versions would be handled on an individual basis by authors themselves.  Since most papers are unlikely to be revised, it’s not worth taking on the challenge of developing a general conversion system from PDF to Markdown that would work reliably.  

Thoughts?  I’m fairly certain there are journals out there that would be interested in migrating their operations to PubPub and it’s something I’ve brought up with people.

**Comment by hrothgar** [comment]
Rather than building a general tool, it might be a better idea (at least while PubPub is small and growing) to develop a conversion tool for each specific journal that wants to migrate. Doing so would be more reliable and would more ensure that journals would smoothly and completely migrate. Of course, this would mean forming a channel by which journals could connect with PubPub about intention to migrate (and it would mean more work for PubPub developers) — but I think getting a few existing journals completely on board is preferable to developing a tool that might not end up being useful to potentially interested parties.

**Comment by gsarma** [comment]
@hrothgar thank you for continuing the discussion.  I absolutely agree with you and perhaps I should have phrased my comment differently.  By "import system," I was really imagining a workflow, rather than a set of software tools or extensions to the platform, although that certainly might be merited in the long run.  

As you say, perhaps the appropriate first step would be to find one journal that would be interested in migrating to PubPub and do a feasibility analysis.

**Comment by gabestein** [comment]
Closing out some old issues...we have a few upcoming migrations and are now preparing to work on a migration tool from a few different platforms. If you're still interested in discussing this, come join us on [Discourse](https://discourse.knowledgefutures.org).
