### ISSUE TITLE
Collection name uniqueness constraint seems to apply across communities

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#858]
**What went wrong, step-by-step?**
1. Go to any community
2. Attempt to create collection with name 'Blog,' get error. (In logs: `2020-06-11T13:12:18.241238+00:00 app[web.5]: SequelizeUniqueConstraintError: Validation error`
3. Attempt to create collection of any type with random name (eg wfjlkregjlkre089-3t4)
4. Attempt to create a collection with that same name and type in the same community, get error.
4. Attempt to create a collection with that same name and different type in the same community, get error.
5. Attempt to create a collection with that same name and type in a different community, get error.
6. 4. Attempt to create a collection with that same name and different type in the same community, get error.
...

**What did you expect to happen?**
I should be able to create a collection in a community with a generic name like "Blog" as long as it doesn't have the same name as another collection in that community.

**What URL can we use to see the issue?**
n/a

**What browser/operating system were you using?**
n/a

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Peter Suber

**Comment by idreyn** [comment]
To summarize discussion on Slack — the root of the problem is that name "Collection Name" is normalized to slug `collection-name` on creation, and there is a uniqueness constraint on collection slugs in the database. Since none of us are sure why it's there, and it's not specified in the Sequelize models from which the database is built, I've gone ahead and dropped it.
