### ISSUE TITLE
Direct URL to draft does not work

### ISSUE THREAD

**Issue by nouyang** [pubpub/pubpub#88]
Going directly to http://miters.pubpub.org/pub/miters-landingpage/draft in the browser does not work for new or recently logged in collaborators, yet going from http://miters.pubpub.org/journal/miters/design to "Edit Landing Page Design" works.

Ubuntu 14.04 Firefox & Chrome
Linux chrome 51.0.2704.103 firefox 47.0a2 chromium 50.0.2661.49

**Comment by nouyang** [comment]
@isTravis  Wow I try not to post comments that are just  :+1: s, but super big thumbs up, this is like everything I've dreamed of and semi-seriously joked about working on for years :) I'd definitely be interested in voluntneering once I'm back in town this fall, and I'll post this to the MITERS keyholders mailing list and see if other folks are interested.

Tagging @JochiPochi @ilebedev @cathywu so they can subscribe to this thread.

**Comment by nouyang** [comment]
Update: I thought of a feature to add to the wishlist.
At MIT we are spoiled to have resources like the CSAIL stockroom or the MIT FabLab / MAS.863 How to Make Anything stockroom. 

However, when most people start a new makerspace or hackerspace or even an academic lab, they often have to build up their own stockroom and parts list and tools list from scratch, which is time-consuming. Not just time, but a lot of money is spent too -- any single group can easily spend thousands of dollars every year on stocking parts.

It would be really great to be able to share these lists, edit these lists, version history them, have images or videos, have links to where to buy them, or links to try to buy subsets of them all at once (for instance, buy all the EE parts on digikey or mouser or something, maybe using the octopart API)
https://blog.octopart.com/archives/category/tools/bom-tool
https://octopart.com/api/docs/v3/overview

(e.g. you can build up orders on McMaster, though you can't make them public, so instead, some screenshots: https://goo.gl/photos/i5C9qG2EHwi3xgkr8 -- 
I think you can reorder everything with one click, but not sure how?).

Further Ideas: the way Amazon implemented "wishlists", or charities and wedding websites implement online gift registries. 

For instance, people collect books on amazon on wishlists:
https://www.amazon.com/gp/registry/wishlist/3GKN9JN2I3YGR/ref=cm_wl_list_o_1?
Wedding gift registry examples:
http://www.zankyou.com/us/why-zankyou/demo-designs

**Comment by isTravis** [comment]
Awesome - yes! Way back in the day I spent a bit of time focusing on web-based collaborative circuit design tools (http://web.media.mit.edu/~trich/surkat/ - looks embarrassing now, but it was a younger me I suppose...).

Anyways, one of the things I've always had in my mind was a fast route for 'make this work for me'. Whether that means ordering parts quickly, having access to data, or having access to computing (getting code, but having to still setup a cluster of machines with a specific version of gentoo and blah blah blah is not actually accessible). 

All that said, I'd be eager and willing to spend some design time or accept a PR on this. Our new architecture (launching quite soon!) will much more cleanly facilitate custom plugins.

In the meantime, because the original intent of this issue is resolved in architecture2 (journal design settings are much more stable), I am going to close this issue.

Feel free to open up a new one to discuss 'BOM support'.
