### ISSUE TITLE
Pub not loading – citation issues

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#913]
**What went wrong, step-by-step?**
1. I noticed that a citation that should have automatically rendered the in-text citation via bibtex was not displaying in the chosen author date format, but as a number (e.g. [34] - I can't remember the number. The citation was Barnes & Gatti, 2019). 
1. I went into the citation and tried to add a couple of blank spaces to the end of the bibtext reference to force the citation to refresh, which has worked in the past. But it didn't. 
1. I then refreshed the page as a whole and it crashed.
1. I did notice that the date is formatted in Zotero (and hence in the Bibtext, presumably) in a very detailed way -- so not just the year or month, but as follows: 2019-05-21T14:28:28.000Z -- in case that's relevant
...

**What did you expect to happen?**
Citation should update properly.

**What URL can we use to see the issue?**
https://copim.pubpub.org/pub/the-promise-of-collaboration/draft
https://sentry.io/organizations/kfg/issues/1710582699/?environment=prod&project=1505439&query=is%3Aunresolved#

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Toby / COPIM

**Comment by isTravis** [comment]
So it looks like this is (thankfully) not a citation loop bug. The issue seems to be when the `structuredData` of a citation is empty, yet we are expecting a label based on the output value of that structured data (i.e. not the simple count). Simply checking for Cite data existence resolves the issue.

PR #915 resolves this. I added Ian for quick review in case there is a better solution upstream that I'm missing.

Tangentially, this bug was a bit tricky to wrangle because of the issue I just created in #916
