### ISSUE TITLE
Refactor HTML/PDF export CSS

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#949]
We changed the way we generate CSS for exports when we moved pubpub-editor into the package. It's time for a refactor of that file to simplify it and provide some better overrides for pdf text sizing.

**Comment by idreyn** [comment]
I keep trying to start this task and continually bang my head against the problem of not being able to `@import` sass files from within mixins or conditionals — without that, the task starts to look like a refactor of all of the Pub body and editor CSS, which I wouldn't say no to, but is an intimidating task.

On the subject of text sizing, though — this should become significantly easier to manage since f65ac325e1b69bf, which pegs all of the font sizes both on the web and in export to values relative to a single parameter — we pass a boolean into the export process to represent a smaller font size, but we could just as easily pass in a specific number instead.
