### ISSUE TITLE
Feature request: better support for math

### ISSUE THREAD

**Issue by hrothgar** [pubpub/pubpub#95]
Although I didn't see it in the markup guide, I discovered that double dollar signs can be used to include inline TeX formulae (which are rendered as images) in the PubPub editor. MathJax would be great to better support math rendering, although getting MathJax and markdown to play nice together can be a pain. Right now it seems that display-style (non-inline) equations are not even possible.

**Comment by isTravis** [comment]
We have a few staged updates to the editor that will provide much better documentation on the math support.

Block math (non-inline) are supported with $$$:

![thkpnrb](https://cloud.githubusercontent.com/assets/1000455/16803112/8afd62e4-48d2-11e6-89d7-e665e7cfa078.png)

What aspects of MathJax are preferable? I personally prefer png/svg rendering of Latex math because 

1. Image files can be pre-rendered, avoiding the 'MathJax Typesetting' message and loop every time equations are loaded.
2. Images can be cached in our CDN and your browser, making them much faster.
3. Images can be more easily copied and shared.

We do need to do a better job of vertically aligning in-line equations (sometimes they appear to high), but that is coming.

**Comment by hrothgar** [comment]
Ah, I didn't try triple dollar signs. But the screenshot you show doesn't look like block math to me; it just looks like inline math on a newline. A block-style `\sum` in LaTeX should put the indices directly above and below the sigma, not in front like a subscript:
![screen shot 2016-07-13 at 11 39 19 am](https://cloud.githubusercontent.com/assets/913747/16809468/765f27de-48ee-11e6-874f-4b53ef6b5bce.png)

Regarding MathJax, I think it just looks better. You're right that the loading time is an issue. But with MathJax you gain control over typographical details like font family, text size, color, and placement. Also there is a problem with background colors. On PubPub if I change the background color from white to something else, I see this:
![screen shot 2016-07-13 at 11 33 28 am](https://cloud.githubusercontent.com/assets/913747/16809577/d2d00858-48ee-11e6-80f3-36004f4565f1.png)

**Comment by isTravis** [comment]
Great points.

We're pushing updates soon that with make the Math rendering/input much more modular. At that point, it'll be quick to alternate to MathJax/SVG render, and decide which is best. I'll post a note here when that is live so we can visit this topic again.

Thanks!

**Comment by isTravis** [comment]
Math support upgraded to use [KaTeX](https://khan.github.io/KaTeX/) in #102. You are very correct in that an HTML representation (be it Mathjax or Katex) provides much more sane line-height defaults, color settings, etc.

Thanks!
