### ISSUE TITLE
Website Social Icon Should Default to #

### ISSUE THREAD

**Issue by writingpoli** [pubpub/pubpub#969]
**What went wrong, step-by-step?**
1. Noticed that when I enter our URL in the Social area of the Settings page it adds the entered URL to the Community URL when live.
2. Can't leave the URL blank in Social area or it hides the icon. 
3. Adding "#" solves the problem for now.

**What did you expect to happen?**

Expected functionality: 
Blank on Social page = Hidden icon on live page
URL on Social = URL on live

**What URL can we use to see the issue?**

/dash/settings

**What browser/operating system were you using?**

Chrome, Windows 10.

---

**Have any screenshots? (Attach them by dragging the image here)**

![image](https://user-images.githubusercontent.com/3883763/89105741-7ad76a80-d3e9-11ea-85cd-7e88161753e5.png)

![image](https://user-images.githubusercontent.com/3883763/89105743-875bc300-d3e9-11ea-83d6-04d7b0f26b76.png)

**Comment by ThomasJorna** [comment]
I think I get what you mean. When you add e.g. `example.com` in the Social > Website field, when you click the icon it will redirect to `sanantoreview.pubpub.org/example.com` right?

I had the same "issue", but it can be easily fixed by entering a full url in the Social > Website field, e.g. `https://example.com`. It then redirects to the correct destination, not a fictional page of your PubPub community.

**Comment by gabestein** [comment]
Thanks Thomas! That's correct, William. You need to use the full domain, with https. We can make that clearer in the settings description.

**Comment by writingpoli** [comment]
Ah ha! Thank you!

-------- Original Message --------
